version: '3.7'
services:
  database: 
    image: postgres
    container_name: database_doctors
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=doctors
      - POSTGRES_PASSWORD=doctors
      - POSTGRES_DB=database_doctors
    volumes:
      - pgdata:/data/postgres

volumes:
  mongodb_data_container:
  pgdata:
    driver: local